# configuration.yml

# logging:
#   level: debug
#   console: true

logging:
  config: logging.yaml


welcome-message: true

web:
  port: 8080
  cors:
    allow-all: true
  command-center:
    enabled: true
    token: secret


databases:
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    database: 7
    password: ${REDIS_PASSWORD}
    reconnect: true


connectors:
  
  websocketmod:
    path: /opsdroid_custom/connectors/websocketmod
    token_key: $SOCKETCONNECTMOD_TOKEN
    bot-name: "mybot" # default "opsdroid"
    max-connections: 10000 # default is 10 users can be connected at once
    connection-timeout: 86400 # default 10 seconds before requested socke
    
 
  matrixmod:
      path: /opsdroid_custom/connectors/matrixmod
      mxid: $MATRIX_USERID
      homeserver: $MATRIX_HOMESERVER
      access_token: $MATRIX_ACCESS_TOKEN
      store: mysql
      device_name: $MATRIX_DEVICE_ID
      device_id: $MATRIX_DEVICE_NAME
      enable_encryption: true
      rooms:
        main: "!grmyiNOcbyGmvDjzTD:matrix.afip.gob.ar"



    # mailconnector:
    #   path: /opsdroid_custom/connectors/mailconnector
    #   username: ${MAIL_USERNAME}
    #   password: ${MAIL_PASSWORD}
    #   update-interval: 60.0
    #   popserver: pop3s1.afip.gob.ar
    #   popport: 995
    #   poptimeout: 60
    #   smtpserver: smtps1.afip.gob.ar
    #   smtpport: 465
    #   smtptimeout: 60
    #   enable: ${MAIL_ENABLE}
    
    
    # telegrampost:
    #   path: /opsdroid_custom/connectors/telegrampost
    #   token: $TELEGRAM_TOKEN 
    #   enable: $TELEGRAM_ENABLE
    #   proxy: $HTTPS_PROXY
    #   update-interval: 15.0
   
#    telegrampostgmail:
#      path: /opsdroid_custom/connectors/telegrampostgmail
#      token: $TELEGRAM_TOKEN_GMAIL
#      enable: $TELEGRAM_ENABLE_GMAIL
#      proxy: $HTTPS_PROXY_GMAIL
#      update-interval: 10.0
    
#    gmailconnector:
#      path: /opsdroid_custom/connectors/gmailconnector
#      username: ${MAIL_USERNAME_GMAIL}
#      password: ${MAIL_PASSWORD_GMAIL}
#      update-interval: 30.0
#      imapserver: imap.gmail.com
#      imapport: 993
#      listening: True
#      #whitelisted_users: [ivo.freisinger@gmail.com]
#      #telegram_chat_id: ${TELEGRAM_CHAT_ID}
#      telegram_chat_id: 651829685 #NO PUDE PASARLO POR VARIABLE NO ESTOY SEGURO QUE HAGA FALTA


#parsers:
#  rasanlu:
#    url: $RASA_URL
#    token: $RASA_TOKEN
#    min-score: 0.8
#    train: False

# parsers:
#   crontab:
#     enabled: true

skills:
  hello:
    path: /opsdroid_custom/skills/skill-hello
    no-cache: false # true, nunca cachea

  me:
    path: /opsdroid_custom/skills/skill-me
    no-cache: false

  autoanswer:
    path: /opsdroid_custom/skills/skill-autoanswer
    no-cache: true
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: 0


  # matrixautojoin:
  #   path: /opsdroid_custom/skills/skill-matrix-autojoin
  #   listen_matrix_only: true
  #   join_when_invited: true
  
  # devops:
  #   path: /opsdroid_custom/skills/skill-devops
  #   dns_default: ${DNS_DEFAULT}
  #   token: ${BEARER_TOKEN}
  #   urls: ${URLS}
  #   #enable: ${OLLAMA_ENABLE}
  
  # ollama:
  #   path: /opsdroid_custom/skills/skill-ollama
  #   enable: ${OLLAMA_ENABLE}
  
  # acl:
  #  path: /opsdroid_custom/skills/skill-acl
  #  admin_users: $ADMIN_USERS

  
  # helper:
  #  path: /opsdroid_custom/skills/skill-helper
  #  admin_users: $ADMIN_USERS

  # grafana:
  #  path: /opsdroid_custom/skills/skill-grafana
  #  token: ${GRAFANA_BEARER_TOKEN}

  # webhook:
  #  path: /opsdroid_custom/skills/skill-webhook
  #  token: ${WEBHOOK_BEARER_TOKEN}